from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

import fitz
from fastapi import APIRouter, File, HTTPException, Response, UploadFile, status
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import FileResponse, JSONResponse, StreamingResponse

from app.core.settings import get_settings
from app.schemas.session import (
    CreateSessionResponse,
    EnsurePageRequest,
    EnsurePageResponse,
    ErrorResponse,
    QualityReport,
    RetryPageResponse,
    RewriteState,
    SaveResultPdfResponse,
    SessionState,
    StartSessionRequest,
    StartSessionResponse,
)
from app.services.events import sse_stream
from app.services.pdf_pipeline import extract_glossary_terms, render_original_pages
from app.services.session_store import SessionPaths, SessionStore
from app.workers.tasks import (
    enqueue_page_if_needed,
    enqueue_rewrite_task,
    enqueue_translation_jobs,
    ensure_pages_enqueued,
)

router = APIRouter(prefix="/sessions", tags=["sessions"])

# Session ids are uuid4 hex strings generated by SessionStore. Validating the
# format at the API boundary keeps untrusted path segments away from file
# path composition (defense in depth).
_SESSION_ID_RE = re.compile(r"^[0-9a-f]{32}$")


def _checked_session_id(session_id: str) -> str:
    if not _SESSION_ID_RE.fullmatch(session_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")
    return session_id


def _priority_page_count(page_count: int) -> int:
    return min(3, page_count)


def _validate_pdf_page_count(content: bytes) -> int:
    try:
        with fitz.open(stream=content, filetype="pdf") as doc:
            return doc.page_count
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Invalid PDF: {exc}") from exc


def _ensure_original_page(paths: SessionPaths, page_no: int) -> Path:
    """Return the original PNG for a page, rendering it on demand if needed.

    Pages render lazily (priority pages at upload, the rest when first
    requested), so callers must tolerate a missing file and render it here.
    """
    file_path = paths.original_dir / f"{page_no}.png"
    if not file_path.exists():
        render_original_pages(paths.source_pdf, paths.original_dir, pages=[page_no])
    return file_path



def _rewrite_state(session_id: str, meta: dict) -> RewriteState:
    raw = meta.get("rewrite") or {}
    return RewriteState(
        session_id=session_id,
        status=raw.get("status", "idle"),
        stage=raw.get("stage"),
        done=int(raw.get("done", 0)),
        total=int(raw.get("total", 0)),
        error=raw.get("error"),
    )


def _export_result_pdf(session_id: str) -> tuple[Path, int, int]:
    """Build the translated PDF by streaming one page at a time into a new
    document via PyMuPDF. Memory stays bounded (one page image at a time)
    instead of holding every page's RGB bitmap at once like PIL save_all.
    """
    _checked_session_id(session_id)
    settings = get_settings()
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")

    page_count = int(meta["page_count"])
    paths = store.paths(session_id)
    export_dir = settings.storage_root / "_saved_results"
    export_dir.mkdir(parents=True, exist_ok=True)
    out_path = export_dir / f"{session_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    try:
        src = fitz.open(paths.source_pdf)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=404, detail="Session file missing") from exc

    translated_pages = 0
    out: fitz.Document | None = None
    try:
        out = fitz.open()
        for page_no in range(1, page_count + 1):
            translated_path = paths.translated_dir / f"{page_no}.png"
            if translated_path.exists():
                image_path: Path = translated_path
                translated_pages += 1
            else:
                try:
                    image_path = _ensure_original_page(paths, page_no)
                except Exception:  # noqa: BLE001
                    continue
            if page_no > src.page_count:
                continue
            src_page = src[page_no - 1]
            new_page = out.new_page(width=src_page.rect.width, height=src_page.rect.height)
            new_page.insert_image(new_page.rect, filename=image_path.as_posix())
        if out.page_count == 0:
            raise HTTPException(status_code=500, detail="No page images available for PDF export")
        out.save(out_path.as_posix(), garbage=3, deflate=True)
    finally:
        src.close()
        if out is not None:
            out.close()

    return out_path, page_count, translated_pages



@router.post("", response_model=CreateSessionResponse, responses={400: {"model": ErrorResponse}})
async def create_session(file: UploadFile = File(...)) -> CreateSessionResponse:
    settings = get_settings()
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Only PDF files are supported")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Empty file")
    if content[:5] != b"%PDF-":
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid PDF header")
    if content[:5] != b"%PDF-":
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid PDF header")

    size_mb = len(content) / (1024 * 1024)
    if size_mb > settings.max_upload_mb:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File exceeds max size of {settings.max_upload_mb}MB",
        )

    size_mb = len(content) / (1024 * 1024)
    if size_mb > settings.max_upload_mb:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File exceeds max size of {settings.max_upload_mb}MB",
        )

    # CPU-bound PDF parsing must not run on the event loop (it would stall
    # every other request and SSE stream for the duration).
    page_count = await run_in_threadpool(_validate_pdf_page_count, content)

    store = SessionStore()
    meta = store.create_session(page_count=page_count)
    session_id = meta["session_id"]
    paths = store.paths(session_id)
    paths.source_pdf.write_bytes(content)

    # Render only priority pages up front; the rest render lazily on first
    # request (see _ensure_original_page) to keep upload response fast.
    priority = list(range(1, _priority_page_count(page_count) + 1))
    await run_in_threadpool(render_original_pages, paths.source_pdf, paths.original_dir, priority)

    return CreateSessionResponse(
        session_id=session_id,
        page_count=page_count,
        expires_at=datetime.fromisoformat(meta["expires_at"]),
    )


@router.post("/{session_id}/start", response_model=StartSessionResponse, responses={404: {"model": ErrorResponse}})
def start_session(session_id: str, request: StartSessionRequest) -> StartSessionResponse:
    _checked_session_id(session_id)
    settings = get_settings()
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")
    page_count = int(meta["page_count"])
    priority = list(range(1, min(3, page_count) + 1))
    if meta["overall_status"] in {"running", "ready"}:
        return StartSessionResponse(status=meta["overall_status"], priority_pages=priority)

    paths = store.paths(session_id)
    if not paths.source_pdf.exists():
        raise HTTPException(status_code=404, detail="Session file missing")

    glossary = extract_glossary_terms(paths.source_pdf, max_terms=settings.glossary_max_terms)
    store.save_providers(
        session_id,
        {
            "primary_provider": request.primary_provider.model_dump(),
            "backup_provider": request.backup_provider.model_dump() if request.backup_provider else None,
            "style_profile": request.style_profile,
            "glossary": glossary,
        },
    )
    store.mark_running(session_id)

    priority = enqueue_translation_jobs(session_id=session_id, page_count=page_count)
    return StartSessionResponse(status="running", priority_pages=priority)


@router.get("/{session_id}/state", response_model=SessionState, responses={404: {"model": ErrorResponse}})
def get_session_state(session_id: str) -> SessionState:
    _checked_session_id(session_id)
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")

    pages = store.list_page_states(session_id)
    warnings_count = sum(len(page.warnings) for page in pages)
    return SessionState(
        session_id=session_id,
        overall_status=meta["overall_status"],
        page_count=int(meta["page_count"]),
        page_states=pages,
        first_readable_ready=store.is_first_readable_ready(session_id),
        warnings_count=warnings_count,
        created_at=datetime.fromisoformat(meta["created_at"]),
        expires_at=datetime.fromisoformat(meta["expires_at"]),
    )


@router.get("/{session_id}/events")
async def get_session_events(session_id: str) -> StreamingResponse:
    _checked_session_id(session_id)
    store = SessionStore()
    if not store.get_meta(session_id):
        raise HTTPException(status_code=404, detail="Session not found")

    return StreamingResponse(sse_stream(session_id), media_type="text/event-stream")


@router.get("/{session_id}/pages/{page_no}/original.png")
def get_original_page(session_id: str, page_no: int) -> FileResponse:
    _checked_session_id(session_id)
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")
    if page_no < 1 or page_no > int(meta["page_count"]):
        raise HTTPException(status_code=404, detail="Page not found")
    paths = store.paths(session_id)
    try:
        file_path = _ensure_original_page(paths, page_no)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail="Failed to render page") from exc
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Page not found")
    # Original pages never change for a given session: safe to cache hard.
    return FileResponse(file_path, headers={"Cache-Control": "private, max-age=31536000, immutable"})


@router.get("/{session_id}/pages/{page_no}/translated.png")
def get_translated_page(session_id: str, page_no: int):
    _checked_session_id(session_id)
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")
    if page_no < 1 or page_no > int(meta["page_count"]):
        raise HTTPException(status_code=404, detail="Page not found")
    file_path = store.paths(session_id).translated_dir / f"{page_no}.png"
    if not file_path.exists():
        return JSONResponse(status_code=202, content={"status": "pending", "page_no": page_no})
    return FileResponse(
        file_path,
        headers={
            "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
            "Pragma": "no-cache",
            "Expires": "0",
        },
    )


@router.post(
    "/{session_id}/pages/{page_no}/ensure",
    response_model=EnsurePageResponse,
    responses={404: {"model": ErrorResponse}},
)
def ensure_page(
    session_id: str,
    page_no: int,
    request: EnsurePageRequest,
) -> EnsurePageResponse:
    _checked_session_id(session_id)
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")

    page_count = int(meta["page_count"])
    if page_no < 1 or page_no > page_count:
        raise HTTPException(status_code=404, detail="Page not found")
    if meta["overall_status"] == "created":
        raise HTTPException(status_code=409, detail="Session not started")

    queued = ensure_pages_enqueued(
        session_id=session_id,
        page_count=page_count,
        center_page=page_no,
        window=request.window,
    )
    return EnsurePageResponse(
        session_id=session_id,
        requested_page=page_no,
        window=request.window,
        queued_pages=queued,
    )


@router.get("/{session_id}/report", response_model=QualityReport, responses={404: {"model": ErrorResponse}})
def get_report(session_id: str) -> QualityReport:
    _checked_session_id(session_id)
    store = SessionStore()
    if not store.get_meta(session_id):
        raise HTTPException(status_code=404, detail="Session not found")
    return store.get_report(session_id)


@router.post("/{session_id}/pages/{page_no}/retry", response_model=RetryPageResponse)
def retry_page(session_id: str, page_no: int) -> RetryPageResponse:
    _checked_session_id(session_id)
    settings = get_settings()
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")

    page_count = int(meta["page_count"])
    if page_no < 1 or page_no > page_count:
        raise HTTPException(status_code=404, detail="Page not found")
    if meta["overall_status"] == "created":
        raise HTTPException(status_code=409, detail="Session not started")

    # Remove old diagnostics for this page so report reflects latest retry result.
    store.clear_report_items_for_page(session_id, page_no)
    # Keep translation memory by default for speed/cost; allow explicit opt-out.
    if settings.clear_translation_memory_on_retry:
        store.clear_translation_memory(session_id)

    store.update_page_state(session_id, page_no, status="pending", error=None)
    queued = enqueue_page_if_needed(session_id=session_id, page_no=page_no, force=True)
    return RetryPageResponse(session_id=session_id, page_no=page_no, status="queued" if queued else "skipped")


@router.post("/{session_id}/save-result-pdf", response_model=SaveResultPdfResponse)
def save_result_pdf(session_id: str) -> SaveResultPdfResponse:
    out_path, page_count, translated_pages = _export_result_pdf(session_id)

    return SaveResultPdfResponse(
        session_id=session_id,
        saved_path=out_path.as_posix(),
        page_count=page_count,
        translated_pages=translated_pages,
    )


@router.get("/{session_id}/export-result.pdf")
def export_result_pdf(session_id: str) -> FileResponse:
    out_path, _, _ = _export_result_pdf(session_id)
    return FileResponse(
        path=out_path,
        media_type="application/pdf",
        filename=f"{session_id}_translated.pdf",
    )


@router.post("/{session_id}/rewrite", response_model=RewriteState, responses={404: {"model": ErrorResponse}})
def start_rewrite(
    session_id: str,
    request: StartSessionRequest | None = None,
) -> RewriteState:
    """Start the in-place rewrite (原位翻译) for the whole document."""
    _checked_session_id(session_id)
    settings = get_settings()
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")

    current = _rewrite_state(session_id, meta)
    if current.status == "running":
        raise HTTPException(status_code=409, detail="Rewrite already running")

    paths = store.paths(session_id)
    if request is not None:
        glossary = extract_glossary_terms(paths.source_pdf, max_terms=settings.glossary_max_terms)
        store.save_providers(
            session_id,
            {
                "primary_provider": request.primary_provider.model_dump(),
                "backup_provider": request.backup_provider.model_dump() if request.backup_provider else None,
                "style_profile": request.style_profile,
                "glossary": glossary,
            },
        )
    elif not store.get_providers(session_id):
        raise HTTPException(status_code=409, detail="Session has no provider config; pass one in the request")

    page_count = int(meta["page_count"])
    store.update_meta(
        session_id,
        rewrite={"status": "running", "stage": "queued", "done": 0, "total": page_count, "error": None},
    )
    enqueue_rewrite_task(session_id)
    return _rewrite_state(session_id, store.get_meta(session_id) or {})


@router.get("/{session_id}/rewrite-state", response_model=RewriteState, responses={404: {"model": ErrorResponse}})
def get_rewrite_state(session_id: str) -> RewriteState:
    _checked_session_id(session_id)
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")
    return _rewrite_state(session_id, meta)


@router.get("/{session_id}/rewrite.pdf", responses={404: {"model": ErrorResponse}})
def export_rewrite_pdf(session_id: str) -> FileResponse:
    _checked_session_id(session_id)
    store = SessionStore()
    meta = store.get_meta(session_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Session not found")
    state = _rewrite_state(session_id, meta)
    if state.status == "running":
        raise HTTPException(status_code=404, detail=f"Rewrite in progress ({state.stage} {state.done}/{state.total})")
    if state.status != "ready":
        raise HTTPException(status_code=404, detail=f"Rewrite not ready (status={state.status})")
    file_path = store.paths(session_id).root / "rewritten.pdf"
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Rewritten PDF not found")
    return FileResponse(
        path=file_path,
        media_type="application/pdf",
        filename=f"{session_id}_inplace.pdf",
    )


@router.delete("/{session_id}", status_code=204)
def delete_session(session_id: str) -> Response:
    _checked_session_id(session_id)
    store = SessionStore()
    if not store.get_meta(session_id):
        return Response(status_code=204)
    store.cleanup_session(session_id)
    return Response(status_code=204)
